# use debian stretch for java 8 and mongodb 3.x
FROM debian:stretch-slim

# set version label
ARG BUILD_DATE
ARG VERSION
ARG UNIFI_VERSION

# environment settings
ARG UNIFI_BRANCH="stable"
ARG DEBIAN_FRONTEND="noninteractive"

RUN \
 echo "**** install packages ****"; \
 apt-get update; \
 for i in $(seq 1 8); do mkdir -p "/usr/share/man/man${i}"; done; \
 apt-get install -y \
        binutils \
        gnupg \
        pcregrep \
        libcap2 \
        logrotate \
        wget \
        curl

RUN \
 apt-get install -y \
        jsvc \
        openjdk-8-jre-headless

RUN \
 echo "**** install mongodb ****" && \
 wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | apt-key add - && \
 echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main" > /etc/apt/sources.list.d/mongodb-org-3.6.list ; \
 apt-get update ; \
 apt-get install -y\
    mongodb-org-server

RUN \
 echo "**** install unifi ****" && \
 if [ -z ${UNIFI_VERSION+x} ]; then \
        UNIFI_VERSION=$(curl -sX GET http://dl-origin.ubnt.com/unifi/debian/dists/${UNIFI_BRANCH}/ubiquiti/binary-amd64/Packages \
        |grep -A 7 -m 1 'Package: unifi' \
        | awk -F ': ' '/Version/{print $2;exit}' \
        | awk -F '-' '{print $1}'); \
 fi && \
 curl -o \
 /tmp/unifi.deb -L \
        "https://dl.ui.com/unifi/${UNIFI_VERSION}/unifi_sysvinit_all.deb" && \
 dpkg -i /tmp/unifi.deb && \
 echo "**** cleanup ****" && \
 apt-get clean && \
 rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/*

# add local files
COPY root/ /

# Volumes and Ports
WORKDIR /usr/lib/unifi
VOLUME /config
EXPOSE 8080 8443 8843 8880